String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'low level communist (CPA vibes)',
    '%4'                    : 'lemon, the leader of the ussr.',
    '%8'                    : 'junior communist country',
    '%16'                   : 'medium communist country',
    '%32'                   : 'senior communist country',
    '%64'                   : 'supersenior communist country',
    '%128'                  : 'peak communist nations',
    '%256'                  : 'hail the russian spy hedgehog',
    '%512'                  : 'josie is chilling here',
    '%1024'                 : 'yo wassup validated',
    '%2048'                 : 'four legs good, two legs better',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'low level communist (CPA vibes)',
    '%p4'                   : 'lemon, the leader of the ussr',
    '%p8'                   : 'junior communist country',
    '%p16'                  : 'medium communist country',
    '%p32'                  : 'senior communist country',
    '%p64'                  : 'supersenior communist country',
    '%p128'                 : 'peak communist nations',
    '%p256'                 : 'hail the russian spy hedgehog',
    '%p512'                 : 'josie is chilling here',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : 'yo wassup validated',
    '%p8192'                : 'four legs good, two legs betterRainbow'

	},

  "en": {
    "%game-intro"           : "Join the <strong>COMMUNIST RANKS!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-COMMUNIST #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'low level communist (CPA vibes)',
    '%4'                    : 'lemon, the leader of the ussr.',
    '%8'                    : 'junior communist country',
    '%16'                   : 'medium communist country',
    '%32'                   : 'senior communist country',
    '%64'                   : 'supersenior communist country',
    '%128'                  : 'peak communist nations',
    '%256'                  : 'hail the russian spy hedgehog',
    '%512'                  : 'josie is chilling here',
    '%1024'                 : 'yo wassup validated',
    '%2048'                 : 'four legs good, two legs better',
    '%4096'                 : '2017 Confetti Vanilla',
    '%8192'                 : 'Rainbow',
    '%p0'                   : 'low level communist (CPA vibes)',
    '%p4'                   : 'lemon, the leader of the ussr',
    '%p8'                   : 'junior communist country',
    '%p16'                  : 'medium communist country',
    '%p32'                  : 'senior communist country',
    '%p64'                  : 'supersenior communist country',
    '%p128'                 : 'peak communist nations',
    '%p256'                 : 'hail the russian spy hedgehog',
    '%p512'                 : 'josie is chilling here',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
    '%p4096'                : 'yo wassup validated',
    '%p8192'                : 'four legs good, two legs betterRainbow'
  }

});
